// Code generated by ogen, DO NOT EDIT.

package apprun_dedicated

// setDefaults set default value of fields.
func (s *HealthCheck) setDefaults() {
	{
		val := int32(30)
		s.IntervalSeconds = val
	}
	{
		val := int32(5)
		s.TimeoutSeconds = val
	}
}
